connectors:
-
  connector_id: ${AZCONFIG_CONNECTOR_ID}
  service_type: "azure_blob_storage"

extraction_service:
  host: http://host.docker.internal:${ES_LOCAL_EXTRACTION_PORT}
  timeout: 30
  use_file_pointers: false
  stream_chunk_size: 65536
  shared_volume_dir: '/app/files'

elasticsearch:
  host: "http://host.docker.internal:${ES_LOCAL_PORT}"
  username: "${ES_LOCAL_USERNAME}"
  password: "${ES_LOCAL_PASSWORD}"
  log_level: INFO
  request_timeout: 120
  max_wait_duration: 60
